name: CI2
on: [push]
jobs:
  call-ci:
    uses: kk-security/.github/.github/workflows/reusable-ci.yml@main
    with:
      node-version: '20'
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  test-composite-action:
     runs-on: [self-hosted,ubuntu-private]
     steps:
        - uses: kk-security/lab-actions@main
          with:
           environment: 'staging'
