name: Solar System Workflow

on: 
  workflow_dispatch: 
  push:
   branches:
    - main
    - 'feature/*'
env:
  MONGO_URI: "mongodb+srv://supercluster.d83jj.mongodb.net/superData"  #this is to pass the env to the apptest.js during unit testing job as that job calls apptest.js which has a field that passes on the env variables.
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:
  unit-testing:
    name: Unit Testing
    # service container is used to connect to databases, web services etc like a test database seperate from the production database
    # https://docs.github.com/en/actions/tutorials/use-containerized-services/use-docker-service-containers
    # to utilize a service container, we must specify the image for the docker image
    # docker host would be the Github runner OS, like ubuntu, windows etc. 
    # need to map the port of the service container to the docker host. such as ports: 12345:27017 would mean the port 27017 of the service container is mapped to the docker host on 12345
    # any step defined under the job will have access to the service container via the localhost port 12345 as all the steps run on the host
    
    services:
      mongo-db:
        image: malla1949/mongo-db:non-prod      # image of a test mongodb image from dockerhub
        ports:
          - 27017:27017

    env:
      MONGO_URI: 'mongodb://localhost:27017/superData'  #add port 27017
      MONGO_USERNAME: non-prod-user
      MONGO_PASSWORD: non-prod-password

    strategy:
      matrix:                                              # use of matrix
        nodejs_version: [18, 19, 20]
        operating_system: [ubuntu-latest]
        exclude:
          - nodejs_version: 18
            operating_system: macos-latest
    runs-on: ${{ matrix.operating_system }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v7
      
      - name: setup NodeJS                                   # installs nodejs
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.nodejs_version }}
      
       # this step is to avoid having to install the dependecies everytime during NPM install
       # https://docs.github.com/en/actions/reference/workflows-and-actions/dependency-caching
      - name: Cache NPM dependencies
        uses: actions/cache@v4
        with:
           # all dependencies are stored in the node_modules folder in our case so path is node_modules
          path: node_modules
          # need to create a unique key. this creates sth like Linux-node-modules-a84cf923... where the "a84cf923" part comes from the package-lock.json file
          # Everytime the dependecies change,developers will update the package-lock.json file and once the package-lock.json changes a new cache is created.
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}


      - name: Install Dependencies
        run: npm install
        
      - name: Unit Testing
        run: npm test

      - name: Archive test results                                # use of archive
        if: always()
        uses: actions/upload-artifact@v7
        with: 
          name: Mocha-Test-Result
          path: test-results.xml  #this is the name of the output file that the unit testing produces. As the output is in root, just the name of file suffices


  code-coverage:
    name: Code Coverage
    # job container is used to run an entire job within a container.
    # for example when the default Github ubuntu runner is preinstalled with software whose version needs to change.
    # we can manually install a new nodejs version on the runner for example, but you dont want each time the runner runs to keep installing the specified nodejs version etc to save github action time

    # also using service container described in above steps
    # as job is running both job and service containers, a container to container communication is required. 
    # https://docs.github.com/en/actions/tutorials/use-containerized-services/create-postgresql-service-containers#running-jobs-in-containers

    container: 
      image: node:18
    services:
      mongo-db:
        image: siddharth67/mongo-db:non-prod   # change localhost to mongo here/ (name of container is mongo as described in options)
        options: 
          --name mongo
           
        # Docker containers on the same user-defined bridge network expose all ports to each other, so you don't need to map any of the service container ports to the Docker host.
        #You can access the service container from the job container using the label you configure in the workflow.
        # therefore no need for the below all ports are available to each other, use label instead:
        # ports:
        #   - 27017:27017

    env:
      MONGO_URI: 'mongodb://mongo:27017/superData'
      MONGO_USERNAME: non-prod-user
      MONGO_PASSWORD: non-prod-password

    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7



      # this step is no longer needed as we running the jobs in container with nodejs installed already
      # - name: Setup NodeJS Version - 18
      #   uses: actions/setup-node@v7
      #   with:
      #     node-version: 18

      # this step is to avoid having to install the dependecies everytime during NPM install
      # https://docs.github.com/en/actions/reference/workflows-and-actions/dependency-caching
      - name: Cache NPM dependencies
        uses: actions/cache@v4
        with:
           # all dependencies are stored in the node_modules folder in our case so path is node_modules
          path: node_modules
          # need to create a unique key. this creates sth like Linux-node-modules-a84cf923... where the "a84cf923" part comes from the package-lock.json file
          # Everytime the dependecies change,developers will update the package-lock.json file and once the package-lock.json changes a new cache is created.
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        run: npm install

      - name: Check Code Coverage
        run: npm run coverage
        continue-on-error: true   #continues to the archive test result step even if the code coverage fails the defined threshold

      - name: Archive test results
        uses: actions/upload-artifact@v7
        with: 
          name: Code-Coverage-Result
          path: coverage
          retention-days: 5 

  docker:
    name: Containerization
    needs: [unit-testing, code-coverage]  # needs to have both the previous jobs to have passed successfully
    runs-on: ubuntu-latest
    permissions: 
      packages: write  # this is to give GITHUB_TOKEN write permission for pushing to Github container registry. Default is only read
    steps:
      #checkout current Repo
      - name: Checkout Repo
        uses: actions/checkout@v7

        # login to Dockerhub 
      - name: Dockerhub login 
        uses: docker/login-action@v4     # https://github.com/marketplace/actions/docker-login
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

        


      # Github Packages Registry -> Container Registry Guide -> https://docs.github.com/en/enterprise-cloud@latest/packages/working-with-a-github-packages-registry/working-with-the-container-registry
      # use github token fror authentication. details in the link above under authentication.
      # at the start of workflows, github automatically creates the GITHUB_TOKEN
      - name: GHCR Login
        uses: docker/login-action@v2.2.0  # https://github.com/marketplace/actions/docker-login
        with:
          registry: ghcr.io                # by default this action always points to the docker registry, so need registry field and specify ghcr.io

          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
        # just test Docker image, dont push to dockerhub yet. this step is needed to give a tag to the local docker image file to load onto the next step.
        # push is set to false 
      - name: Docker Build for Testing
        uses: docker/build-push-action@v7   # https://github.com/marketplace/actions/build-and-push-docker-images
        with: 
          context: .                         # this is the path to the docker file. In our case its in the root dir
          push: false
          tags: ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}  
          # The tag works like the image’s exact name/identifier. For example, GitHub may convert it to: mallashrey/solar-system:a8f52c9
      
        
        # Docker image testing
      - name: Docker Image Testing
        # docker is already installed in runners so this lists docker images, runs a docker container and names it solar-system-app
        # -d runs in detached mode. -e passes the environment variables needed for the app
        # run the image built above using the same tag - tag: ${{ env.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}
        # get the IP address with the export IP command below
        # in this case the IP is just for demo purpose and we are not making use of it as the application is running on localhost
        # we use wget. the app uses /live endpoint.
        run: |
          docker images                                     
          docker run --name solar-system-app -d \
            -p 3000:3000 \
            -e MONGO_URI=$MONGO_URI \
            -e MONGO_USERNAME=$MONGO_USERNAME \
            -e MONGO_PASSWORD=$MONGO_PASSWORD \
            ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}

          export IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' solar-system-app)
          echo $IP

          echo Testing Image URL using wget
          wget -q -O - 127.0.0.1:3000/live | grep live

        
        # actually push the docker image now to docker hub and container registry. Push is true. Copied same steps from "Docker build for Testing" step
      - name: Push to docker and container registry
        uses: docker/build-push-action@v7   # https://github.com/marketplace/actions/build-and-push-docker-images
        with: 
          context: .                         # this is the path to the docker file. In our case its in the root dir
          push: true
          # using the tag as the docker image identifier. pushes the docker image to docker and to github container registry under packages
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}   
            ghcr.io/${{ github.repository_owner }}/solar-system:${{github.sha}}



  dev-deploy:
    if: contains(github.ref, 'feature/')
    needs: docker
    # deploy to development environment
    environment: 
      name: development
      url: https://${{ steps.setup-ingress-host-address.outputs.APP_INGRESS_HOST }}
    runs-on: ubuntu-latest
    outputs: 
      APP_INGRESS_URL: ${{ steps.setup-ingress-host-address.outputs.APP_INGRESS_HOST }}   # this is for the job to job pass of outputs for ingress in "Deploy to dev" env step
      # https://docs.github.com/en/actions/how-tos/write-workflows/choose-what-workflows-do/pass-job-outputs
      # once the outputs are set at the job level, I can use them in other jobs
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install kubectl CLI
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.26.0'

      - name: Set Kubeconfig File
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Fetch Kubernetes Cluster Details
        run: |
          kubectl version --short
          echo "--------------------------------------------------"
          kubectl get nodes
          
      - name: Save Nginx Ingress Controller IP as a GitHub Environment Variable
          # github env is for setting sth as a environment variable from a job step, that other jobs and steps can use. in this case IngressIP is stored as INGRESS_IP under GITHUB_ENV which is later used
          # https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-commands#setting-an-environment-variable
        run: |
          echo "INGRESS_IP=$(kubectl -n ingress-nginx get services ingress-nginx-controller -o jsonpath='{.status.loadBalancer.ingress[0].ip}')" >> "$GITHUB_ENV"

      - name: Replace Token in Manifest Files
        # this is to replace the token in kuberenetes/deployment/deployment.yml _{_REPLICAS_}_ etc
        # https://github.com/marketplace/actions/replace-tokens
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '_{_'
          tokenSuffix: '_}_'
          files: '["kubernetes/development/*.yaml"]'  # path to the yaml files for kubernetes
        env:
          NAMESPACE: ${{ vars.NAMESPACE }}
          REPLICAS: ${{ vars.REPLICAS }}
          IMAGE: ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}
          INGRESS_IP: ${{ env.INGRESS_IP }}           # use of GITHUB_ENV from above

      
      - name: Check files
        run: | 
          cat kubernetes/development/*.yaml


        #this step is needed before deploying to kubernetes. this is because the deployment.yml kubernetes file requires these secrets
      - name: Create MongoDB Secret
        run: |
          kubectl -n ${{ vars.NAMESPACE }} create secret generic mongo-db-creds \
            --from-literal=MONGO_URI=${{ env.MONGO_URI }} \
            --from-literal=MONGO_USERNAME=${{ vars.MONGO_USERNAME }} \
            --from-literal=MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }} \
            --save-config \
            --dry-run=client \
            -o yaml | kubectl apply -f -

      - name: Deploy to dev env
        id: setup-ingress-host-address         # this id is used for setting up a job to job pass of outputs 
        run: |
          kubectl apply -f kubernetes/development
      
      - name: Set App Ingress Host URL
        id: set-ingress-host-address
        run: |
          echo "APP_INGRESS_HOST=$(kubectl -n ${{ vars.NAMESPACE }} get ingress -o jsonpath='{.items[0].spec.tls[0].hosts[0]}')" >> "$GITHUB_OUTPUT"

  dev-integration-testing:
    if: contains(github.ref, 'feature/')
    # basic integration testing
    name: Dev Integration Testing
    needs: dev-deploy
    runs-on: ubuntu-latest

    steps:
      - name: Test URL Output using CURL and JQ
        env:
          URL: ${{ needs.dev-deploy.outputs.APP_INGRESS_URL }} # job to job output sharing for the ingress IP. need to do this as the IP is dynamic
          # https://docs.github.com/en/actions/how-tos/write-workflows/choose-what-workflows-do/pass-job-outputs
        run: |
          echo $URL
          echo "--------------------------------------------------"
          curl https://$URL/live -s -k | jq -r .status | grep -i live




  # production
  prod-deploy:
    if: github.ref == 'refs/heads/main'
    needs: docker
    # deploy to production environment
    environment: 
      name: production
      url: https://${{ steps.setup-ingress-host-address.outputs.APP_INGRESS_HOST }}
    runs-on: ubuntu-latest
    outputs: 
      APP_INGRESS_URL: ${{ steps.setup-ingress-host-address.outputs.APP_INGRESS_HOST }}   # this is for the job to job pass of outputs for ingress in "Deploy to dev" env step
      # https://docs.github.com/en/actions/how-tos/write-workflows/choose-what-workflows-do/pass-job-outputs
      # once the outputs are set at the job level, I can use them in other jobs
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install kubectl CLI
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.26.0'

      - name: Set Kubeconfig File
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Fetch Kubernetes Cluster Details
        run: |
          kubectl version --short
          echo "--------------------------------------------------"
          kubectl get nodes
          
      - name: Save Nginx Ingress Controller IP as a GitHub Environment Variable
          # github env is for setting sth as a environment variable from a job step, that other jobs and steps can use. in this case IngressIP is stored as INGRESS_IP under GITHUB_ENV which is later used
          # https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-commands#setting-an-environment-variable
        run: |
          echo "INGRESS_IP=$(kubectl -n ingress-nginx get services ingress-nginx-controller -o jsonpath='{.status.loadBalancer.ingress[0].ip}')" >> "$GITHUB_ENV"

      - name: Replace Token in Manifest Files
        # this is to replace the token in kuberenetes/deployment/deployment.yml _{_REPLICAS_}_ etc
        # https://github.com/marketplace/actions/replace-tokens
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '_{_'
          tokenSuffix: '_}_'
          files: '["kubernetes/production/*.yaml"]'  # path to the yaml files for kubernetes
        env:
          NAMESPACE: ${{ vars.NAMESPACE }}
          REPLICAS: ${{ vars.REPLICAS }}
          IMAGE: ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}
          INGRESS_IP: ${{ env.INGRESS_IP }}           # use of GITHUB_ENV from above

      
      - name: Check files
        run: | 
          cat kubernetes/production/*.yaml


        #this step is needed before deploying to kubernetes. this is because the deployment.yml kubernetes file requires these secrets
      - name: Create MongoDB Secret
        run: |
          kubectl -n ${{ vars.NAMESPACE }} create secret generic mongo-db-creds \
            --from-literal=MONGO_URI=${{ env.MONGO_URI }} \
            --from-literal=MONGO_USERNAME=${{ vars.MONGO_USERNAME }} \
            --from-literal=MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }} \
            --save-config \
            --dry-run=client \
            -o yaml | kubectl apply -f -

      - name: Deploy to prod env
        id: setup-ingress-host-address         # this id is used for setting up a job to job pass of outputs 
        run: |
          kubectl apply -f kubernetes/production

      - name: Set App Ingress Host URL
        id: set-ingress-host-address
        run: |
          echo "APP_INGRESS_HOST=$(kubectl -n ${{ vars.NAMESPACE }} get ingress -o jsonpath='{.items[0].spec.tls[0].hosts[0]}')" >> "$GITHUB_OUTPUT"    

  prod-integration-testing:
    if: github.ref == 'refs/heads/main'
    # basic integration testing
    name: Prod Integration Testing
    needs: prod-deploy
    runs-on: ubuntu-latest

    steps:
      - name: Test URL Output using CURL and JQ
        env:
          URL: ${{ needs.prod-deploy.outputs.APP_INGRESS_URL }} # job to job output sharing for the ingress IP. need to do this as the IP is dynamic
          # https://docs.github.com/en/actions/how-tos/write-workflows/choose-what-workflows-do/pass-job-outputs
        run: |
          echo $URL
          echo "--------------------------------------------------"
          curl https://$URL/live -s -k | jq -r .status | grep -i live
    







          